language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -qr ereports/requirements/install.pip
  - pip install -qr ereports/requirements/testing.pip

script: py.test -vv
